### PR TITLE
Bumped glutin to 0.19.0

### PR DESCRIPTION
**Pull request by 0e4ef622**
Fixes a window title bug.

### CODE REVIEW

**Comment by bvssvni** [comment]
This is not a breaking change. Could bump the patch.

**Comment by bvssvni** [comment]
Hmm? That's the same commit twice. I guess something went wrong.

**Comment by 0e4ef622** [comment]
Yeah I forgot to add a thing to the commit

**Comment by bvssvni** [comment]
Did you remember to bump the patch instead of the minor version?

**Comment by 0e4ef622** [comment]
I didn't bump the version of this crate, just the version of the dependency.

**Comment by bvssvni** [comment]
Ah. Sorry. Yes, that's a breaking change. I'll make another PR when this gets merged.

**Comment by bvssvni** [comment]
Merging.

**Pull request merged**
