### PR TITLE
Fixed scaling bug

### PR DESCRIPTION
**Pull request by bvssvni**
Closes https://github.com/PistonDevelopers/glutin_window/issues/145

### CODE REVIEW

**Comment by bvssvni** [comment]
cc @0e4ef622 @arnodb

**Comment by arnodb** [comment]
It looks like it's working well, perfect. Feel free to close #148 when this one is merged.

**Comment by 0e4ef622** [comment]
Looks good to me.

**Comment by 0e4ef622** [comment]
Actually I just noticed, shouldn't a Resize event give the new size in points? The docs don't say, and this code is returning the new size in physical pixels. And in the same vein, glutin should be able to handle all the dpi stuff and as I understand it, piston's "points" are equivalent to glutin's "logical pixels", so there really shouldn't be any dpi scaling in this library except for Window::draw_size.

**Comment by bvssvni** [comment]
@0e4ef622 You're right.

**Comment by arnodb** [comment]
Interesting, I thought my app was asking for a window size in pixels but, after reading the doc `Size` is supposed to be in points and `WindowSettings` is asking for a `Size`. That means that the app should convert the resize events back to pixels (if eventually it contains points in the future) so that I can pass the pixels to the OpenGL calls. Do you confirm?

**Comment by bvssvni** [comment]
@arnodb Yes, that's correct. Resize events is supposed to be in points.

**Pull request merged**
