### PR TITLE
Add MouseRelative events

### PR DESCRIPTION
**Pull request by mattico**
cc @bvssvni 

I'm pretty sure these aren't missing intentionally?

### CODE REVIEW

**Comment by bvssvni** [comment]
This is a delicate matter. When pushing to an event overflow stack and then popping them reverses the order, which might mess up application logic. Use a queue or an extra field for relative events like sdl2_window (https://github.com/PistonDevelopers/sdl2_window/blob/master/src/lib.rs#L54). The returned event need to be consistent with the order, which probably should follow SDL2.

The [user_input](https://github.com/PistonDevelopers/piston-examples/tree/master/user_input) example is used to test the window backends. The SDL2 backend is the one with fewest bugs, so I usually just use it if there are problems with Glutin and then post an issue to not forget it.

Designing the behavior of the window backends require my full attention in order to not introduce new bugs. I wrote up the design for cursor events [here](https://github.com/PistonDevelopers/piston/issues/962). I hope that I thought this through properly at that time, but need another round if I didn't.

Sorry, but I work on other stuff at the moment. Can we put this PR on hold? Touch events are not added yet, which I planned to get around to when I'm finished with the 2D graphics upgrade. However, I will probably need another break to charge my batteries before then. If you want to work on this, that is fine by me, but you need to write everything down in detail and think it through, then wait a while to see if there is something you did not thought of, and then test it. It is a slow process, and you might be better off by using the SDL2 backend in the meantime.

**Comment by mattico** [comment]
Fair enough. Thanks for the consideration. If I find time, I'll start working on this properly.

**Comment by psFried** [comment]
Currently, Conrod expects window backends to supply `MouseCursor` instead of `MouseRelative` events. We could easily change Conrod to accept either event type, but I think there's a bigger question here. Window backends should all provide mouse motion events in the same way. If we want to say that all the mouse moves should be relative, that might make sense, but I think we should agree to be consistent. Has that conversation been going on elsewhere?

**Comment by bvssvni** [comment]
I've added relative mouse events in https://github.com/PistonDevelopers/glutin_window/pull/87.

Closing.

**Pull request closed without merging**
