### PR TITLE
Fix cursor move event coordinates

### PR DESCRIPTION
**Pull request by 0e4ef622**
Related to [this comment](https://github.com/PistonDevelopers/glutin_window/pull/149#issuecomment-438328619).

### CODE REVIEW

**Comment by bvssvni** [comment]
Have you tested this on your setup? Can you tell me the window size and coordinates in the lower right corner emitted by mouse events with and without this patch?

Also, should not the resize event be fixed too?

**Comment by 0e4ef622** [comment]
Yes I have tested it, the reason I found it was because a button was activating when it shouldn't have been. As for resize event, I wanted to change that too but I wasn't sure so I held off.

**Comment by 0e4ef622** [comment]
I threw together a little program, the red square is where piston thinks my mouse is. My mouse is actually in the lower right corner in both screenshots as you asked.

Without the patch:
without the patch

With the patch:
with the patch

**Comment by bvssvni** [comment]
Thanks! I will make another PR for the Resize event.

**Pull request merged**
